### ISSUE TITLE
Documentation for use of VFSMS 

### ISSUE THREAD

**Issue by vs74** [Keep-Passion/ImageStitch#4]
Hi it's a really nice  and interesting repo. Could you provide a documentation on how to use VFSMS . That would be really appreciated as I need to experiment with VFSMS on the images for my project.
Thnx in advance!!

**Comment by MATony** [comment]
Thanks for your advisement. I will add documentation for use of VFSMS in the future. I will reply to you after i have finished it. However, please forgive me that i can not ensure the duration because i am very busy this time. If you meet some problems, please tell me and i try to reply to you as soon as possible. That will save time for your project. Could you briefly tell me your problem? Do you need GPU version or CPU version?

**Comment by vs74** [comment]
Thanks for reply. I would requiring VFSMS for stitching of SEM/TEM microscopy images. As per the CPU/GPU version concerned, I am not sure about it which one I would be requiring. Could you give some direction to proceed with VFSMS?

**Comment by MATony** [comment]
Well, i have implemented both of them. However, GPU version could only be applied to windows operation system by now. In addition, be careful of your version of python and opencv. I recommend to use python3.6 and opencv-contrib-python 3.3.1. If you want to use GPU version, please download 'myGpuFeatures' in readme.md and unzip it in your project address, then run Main.py. If you want to use CPU version, please set Stitcher.isGPUAvailable = False

**Comment by MATony** [comment]
I have uploaded the GPU file in rar data at github, you can download and unrar it if you use our codes on windows platform

**Comment by vs74** [comment]
Thanks @MATony  for quick turnaround.
