### ISSUE TITLE
Support for RGB images

### ISSUE THREAD

**Issue by Matt1700** [Keep-Passion/ImageStitch#6]
Really great software, I'm currently using it to stitch aerial pictures taken from a moving camera. Even though it's not its intended use it works really well. Could you make full-color pictures supported? Because I've tried to change cv2.IMREAD_GRAYSCALE to cv2.IMREAD_COLOR and it throws an error. Probably because the NumPy array is one dimensional. If you tell me how to do it I can make the changes myself. Thanks.

**Comment by Keep-Passion** [comment]
Thanks for your advisement. Because microscopic image always have one channel, so i didn't consider RGB image. But you can change it as you wish. I split my stitch algorithm into two parts: image registering and image stitching. In image registering, the method find offset by feature detection algorithm, such as sift or surf. They need gray scale image to find key point and its descriptor, that's why i input gray image. So you don't need to change this. You can change the second part. In  function 'getStitchByOffset' and 'fuseImage' at Stitcher.py. But i think you might meet some trouble in image fusion, i recommand to use 'fuseByFadeInAndFadeOut' and 'fuseByAverage' to test, be careful to the shape of image. I am a little busy now, i will change this in the future.  Finally, Be careful of your scene. Microscopic image stitching is parallel stitching, so i just consider the offset (dx, dy), but i doubt aerial pictures might occurs affine transformation and small distortion, where my method can't handle it, you should notice that.

**Comment by Matt1700** [comment]
Done! It's easier than it seems, I just changed a couple of variables in 'getStitchByOffset', it even works with trigonometric fuse method. As for the parallel stitching, it shouldn't be a problem because the camera is fixed on a moving axis about 1 meter in the air and points to the ground so the only movement that it does is forward or backwards. Thanks and have a nice day!

**Comment by Keep-Passion** [comment]
You're welcome. If you feel helpful, please star my respositore and cite my paper when you publish your work

**Comment by Keep-Passion** [comment]
You're welcome. If you feel helpful, please star my respositore and cite my paper when you publish your work

**Comment by Gunith1** [comment]
> Done! It's easier than it seems, I just changed a couple of variables in 'getStitchByOffset', it even works with trigonometric fuse method. As for the parallel stitching, it shouldn't be a problem because the camera is fixed on a moving axis about 1 meter in the air and points to the ground so the only movement that it does is forward or backwards. Thanks and have a nice day!

**Can I know what variables ya have changed?
I'm working on microscopic images and I want to use rgb pictures**

**Comment by Keep-Passion** [comment]
> > Done! It's easier than it seems, I just changed a couple of variables in 'getStitchByOffset', it even works with trigonometric fuse method. As for the parallel stitching, it shouldn't be a problem because the camera is fixed on a moving axis about 1 meter in the air and points to the ground so the only movement that it does is forward or backwards. Thanks and have a nice day!
> 
> **Can I know what variables ya have changed? I'm working on microscopic images and I want to use rgb pictures**

Because not all fusion methods are support for RGB images and many microscopic images are gray-scale, I did not consider RGB two years ago. For your convinence, I have just create a new branch, notStableForColor, we just test FadeInAndFadeOut. This fusion mode is ok now for rgb fusion, please try that

**Comment by Gunith1** [comment]
> > > Done! It's easier than it seems, I just changed a couple of variables in 'getStitchByOffset', it even works with trigonometric fuse method. As for the parallel stitching, it shouldn't be a problem because the camera is fixed on a moving axis about 1 meter in the air and points to the ground so the only movement that it does is forward or backwards. Thanks and have a nice day!
> > 
> > 
> > **Can I know what variables ya have changed? I'm working on microscopic images and I want to use rgb pictures**
> 
> Because not all fusion methods are support for RGB images and many microscopic images are gray-scale, I did not consider RGB two years ago. For your convinence, I have just create a new branch, notStableForColor, we just test FadeInAndFadeOut. This fusion mode is ok now for rgb fusion, please try that

okay thank you. great work!
