### ISSUE TITLE
Output is not correct

### ISSUE THREAD

**Issue by Gunith1** [Keep-Passion/ImageStitch#7]
I read this is specially for microscopic images but this is not working on my images. I'm working on breast cancer image analysis. I'm attaching images too. Hoping you would have some solution. Thank you.

![stitching_result_1_5](https://user-images.githubusercontent.com/46871660/86429893-6d599280-bd0e-11ea-9a39-03d784c43d42.jpg)
![IMG20200624112908](https://user-images.githubusercontent.com/46871660/86429911-79ddeb00-bd0e-11ea-93cf-95ba93fb67b1.jpg)
![IMG20200624112911](https://user-images.githubusercontent.com/46871660/86429912-7ba7ae80-bd0e-11ea-8169-471428463df8.jpg)

**Comment by Gunith1** [comment]
and when I try to use gpu version it shows this error

  from myGpuFeatures import myGpuFeatures
ImportError: DLL load failed: The specified module could not be found.

I'm not sure how to solve this.

**Comment by Keep-Passion** [comment]
The two images which need to be stitched must have overlap region, i can not find the overlap region in your example, both RGB or gray-scale. Beside, in our examples, there are no circle background region,i think that's why your stitching result have incorrect result. Please see our examples and try to find the difference between with your images.
Besides, if you want to use GPU mode, you should unzip the file “myGpuFeatures.rar”

**Comment by Keep-Passion** [comment]
I think fade in and fade out is not used for your images, flease try to use 'notFuse' mode

**Comment by roshan64** [comment]
Hello,even if i unzipped “myGpuFeatures.rar” i am getting same error as gunith1.

ImportError: DLL load failed: The specified module could not be found.

**Comment by Keep-Passion** [comment]
> Hello,even if i unzipped “myGpuFeatures.rar” i am getting same error as gunith1.
> 
> ImportError: DLL load failed: The specified module could not be found.
> 
> And when i use maximum as fuseMethod there are visible seams in stitched images.What should i do to remove that seams?
> Thanks.

When I write my code, tha patent of SIFT is not expired. So that opencv can not provide the GPU version og SIFT, but it's have that in its contrib. (only in opencv 3.3.1, and can not find in Opencv3.4). So that i rebuild to dll and run it on my windows operating system. I only test python 36 and (opencv-contrib-python 3.3.1.11), please check that.

Visible seam can be addressed by fusion method. We provide some fusion mode in our work. Generally, the fade in and fade out mode or triangle fusion mode can work on this in there is no object moving in the images. But according to the situation of @Gunith1 's images. I recomennd to filter the dark region out when fusing two overlaping regions.

**Comment by roshan64** [comment]
Thanks for quick reply,my opencv and opencv-contrib and python versions are same as u mentioned.Though i am getting same error
  from myGpuFeatures import myGpuFeatures
ImportError: DLL load failed: The specified module could not be found.

**Comment by Keep-Passion** [comment]
> Thanks for quick reply,my opencv and opencv-contrib and python versions are same as u mentioned.Though i am getting same error
> from myGpuFeatures import myGpuFeatures
> ImportError: DLL load failed: The specified module could not be found.

Please checking the location of its folder??
![image](https://user-images.githubusercontent.com/6437651/86470620-59457d80-bd6e-11ea-8de7-5aea4735875c.png)

**Comment by roshan64** [comment]
![image](https://user-images.githubusercontent.com/58878348/86471077-4759df80-bd5a-11ea-8f4e-e82ccf731de0.png)
yeah its in same folder as urs

**Comment by Keep-Passion** [comment]
I am sorry i don't know this reason, i have checked that on different windows operationg system on different computers two years ago....It's ok now on my win10 operating system. Or you can check your GPU, this is only support for cuda of nvidia.

**Comment by Gunith1** [comment]
Sorry to bother you so much but I have nvidia but still I cant use gpu version the same error pops everytime.
I'll explain the whole scenario if you have time do read and help me out
there are set are 10 images and when i input that images to an app bimostitch this is the output
![x](https://user-images.githubusercontent.com/46871660/86494352-62e0dc80-bd92-11ea-8172-5bb3c921d832.jpeg)

but when i input that 10 images to this algorithm many images arent stitched and the ones which are stitched have visible seams
![stitching_result_1_4](https://user-images.githubusercontent.com/46871660/86494402-9885c580-bd92-11ea-8d7f-6ff6229a51d5.jpeg)

since this algorithm is specially for microscopic images I'm expecting this to work on our problem.
just tell me few things will there be any change if we use gpu version in the output ?
I have another output
![y](https://user-images.githubusercontent.com/46871660/86494539-2feb1880-bd93-11ea-9728-c4cb510c3684.jpeg)

is there anything we can do to remove those black bands?
if you have any answers please help me out. thank so far.

**Comment by Keep-Passion** [comment]
The difference between your images and our examples is the shape of imaging. The region outside your circle imaging area is the black background. When you use fade in and fade out mode, the balck pixel influence the calculation of fusion. Please give me your example images and I will modify our code to suit to your situation. Or you can change the function in def fuse_by_fade_in_and_fade_out in ImageFusion.py

**Comment by Gunith1** [comment]
yeah okay 793960628@qq.com ist this your mail? if so i have sent it.

**Comment by Keep-Passion** [comment]
Yes, it is my email. And I have received that. Alough it's weekend in china, i have some works needed to be done. Please give me one or two days to finish your example.

**Comment by Gunith1** [comment]
yeah sure thanks.

**Comment by Keep-Passion** [comment]
I have tried to modify our algorithm for your images and made changes in the branch NotStableForColor.
However, I can't handle it very well according to your data structure.
First, the order of file. I assume that the order of file name is consistent with the order of actual stitching. The first image and second image should have overlap region. The APP BioStitch address well on disorder file names. But i think it will spend more time. 
Second, there is a blue circle around your picture which impact the result of fade in and fade out mode, as shown in red arrow. So that I can't remove that by simple thresholding method in image fusion. An exmaple is shown here:
![image](https://user-images.githubusercontent.com/6437651/86535948-7d43c300-bf16-11ea-9f0b-df0a27880a2a.png)
Besides，i recommend you to use ImageJ, a commonly used publicly software implemented by Java, may be useful for your coding. Bus as far as i known, it use phase correlation stitching method and not feature based methods. That is it can't tell you two images cannot be stitched. The result of imageJ is not stable.

**Comment by Keep-Passion** [comment]
By the way, i think you can preprocess the images. You can draw a big circle in your image and cut the region outside circle (including blue circle region), I think it is bascally no information loss but have better visualization result.

**Comment by Gunith1** [comment]
Thank you so much for you help. I'll tryout your suggestions.
